run_dir: "CHANGE_ME" # Directory containing MKV files.
sub_dir: "processed" # Directory under run_dir containing exported color/depth images.
calibration_frame: 0
all_serials:
  - "000033103112"
  - "000192203112"
  - "000260603112"
  - "000512692212"
  - "000541403212"
  - "000545703212"
  - "000614303212"
  - "000828303212"

checkerboard_size: [11, 8] # Inner corners: columns, rows.
square_size: 0.03 # Meters.

hydra:
  output_subdir: .hydra
  run:
    dir: hydra_logs/${hydra.job.name}/${now:%Y%m%d_%H%M%S}
  sweep:
    dir: hydra_logs/${hydra.job.name}
    subdir: multirun
  job:
    chdir: false
