record:
  output_dir: recordings
  master_serial: "000192203112"
  resolution: "720p"
  fps: 30
  subordinate_delay_usec: 160
  synchronized_images_only: true
  # 分布式参数↓  每台电脑相应修改！！！
  start_rank: 3
  machine_tag: "node1"

# 预览参数，不建议修改
preview:
  width: 320
  height: 180

hydra:
  output_subdir: .hydra
  run:
    dir: hydra_logs/${hydra.job.name}/${now:%Y%m%d_%H%M%S}
  sweep:
    dir: hydra_logs/${hydra.job.name}
    subdir: multirun
  job:
    chdir: false
