run_dir: "recordings/20260417_121333" # windows 路径，注意双斜杠\\
output_subdir: "processed"
fps: 30
all_serials:
  - "000033103112"
  - "000192203112"
  # - "000260603112"
  # - "000512692212"
  - "000541403212"
  - "000545703212"
  - "000614303212"
  - "000828303212"

# hydra 配置，不建议修改
hydra:
  output_subdir: .hydra
  run:
    dir: hydra_logs/${hydra.job.name}/${now:%Y%m%d_%H%M%S}
  sweep:
    dir: hydra_logs/${hydra.job.name}
    subdir: multirun
  job:
    chdir: false
